x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_meta
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://localhost:8080/execution/"
    WAREHOUSE_URL: postgresql://airflow:airflow@postgres:5432/covid
    WAREHOUSE_HOST: postgres
    WAREHOUSE_USER: airflow
    WAREHOUSE_PASSWORD: airflow
    WAREHOUSE_DB: covid
    DBT_PROFILES_DIR: /opt/airflow/dbt/covid_dbt
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./dbt:/opt/airflow/dbt
    - airflow_data:/opt/airflow/data
  depends_on:
    postgres:
      condition: service_healthy
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_MULTIPLE_DATABASES: "airflow_meta,covid"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    user: root
    command:
      - -c
      - "mkdir -p /opt/airflow/data/raw && chown -R airflow:root /opt/airflow/data && airflow db migrate"
  airflow-standalone:
    <<: *airflow-common
    command: airflow standalone
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      WAREHOUSE_URL: postgresql://airflow:airflow@postgres:5432/covid
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  airflow_data: